<?php

$traducoesNomes = [
    'Affenpinscher' => 'Affenpinscher', 'Afghan Hound' => 'Galgo Afegão', 'African Hunting Dog' => 'Cão de Caça Africano',
    'Airedale Terrier' => 'Airedale Terrier', 'Akbash Dog' => 'Akbash', 'Akita' => 'Akita',
    'Alapaha Blue Blood Bulldog' => 'Alapaha Blue Blood Bulldog', 'Alaskan Husky' => 'Husky do Alasca', 'Alaskan Malamute' => 'Malamute do Alasca',
    'American Bulldog' => 'Buldogue Americano', 'American Bully' => 'American Bully', 'American Eskimo Dog' => 'Cão Esquimó Americano',
    'American Foxhound' => 'Foxhound Americano', 'American Pit Bull Terrier' => 'Pit Bull', 'American Staffordshire Terrier' => 'American Staffordshire Terrier',
    'American Water Spaniel' => 'Spaniel d\'Água Americano', 'Anatolian Shepherd Dog' => 'Pastor da Anatólia', 'Appenzeller Sennenhund' => 'Boiadeiro de Appenzell',
    'Australian Cattle Dog' => 'Boiadeiro Australiano', 'Australian Kelpie' => 'Kelpie Australiano', 'Australian Shepherd' => 'Pastor Australiano',
    'Australian Terrier' => 'Terrier Australiano', 'Azawakh' => 'Azawakh', 'Barbet' => 'Barbet', 'Basenji' => 'Basenji',
    'Basset Bleu de Gascogne' => 'Basset Azul da Gasconha', 'Basset Hound' => 'Basset Hound', 'Beagle' => 'Beagle',
    'Bearded Collie' => 'Bearded Collie', 'Beauceron' => 'Beauceron', 'Bedlington Terrier' => 'Bedlington Terrier',
    'Belgian Malinois' => 'Pastor Belga Malinois', 'Belgian Tervuren' => 'Pastor Belga Tervuren', 'Bernese Mountain Dog' => 'Boiadeiro de Berna',
    'Bichon Frise' => 'Bichon Frisé', 'Black and Tan Coonhound' => 'Coonhound Preto e Castanho', 'Bloodhound' => 'Cão de Santo Humberto (Bloodhound)',
    'Bluetick Coonhound' => 'Bluetick Coonhound', 'Boerboel' => 'Boerboel', 'Border Collie' => 'Border Collie', 'Border Terrier' => 'Border Terrier',
    'Boston Terrier' => 'Boston Terrier', 'Bouvier des Flandres' => 'Boiadeiro da Flandres', 'Boxer' => 'Boxer', 'Boykin Spaniel' => 'Boykin Spaniel',
    'Bracco Italiano' => 'Braco Italiano', 'Briard' => 'Briard', 'Brittany' => 'Spaniel Bretão', 'Bull Terrier' => 'Bull Terrier',
    'Bull Terrier (Miniature)' => 'Bull Terrier Miniatura', 'Bullmastiff' => 'Bullmastiff', 'Cairn Terrier' => 'Cairn Terrier',
    'Cane Corso' => 'Cane Corso', 'Cardigan Welsh Corgi' => 'Welsh Corgi Cardigan', 'Catahoula Leopard Dog' => 'Cão Leopardo de Catahoula',
    'Caucasian Shepherd (Ovcharka)' => 'Pastor do Cáucaso', 'Cavalier King Charles Spaniel' => 'Cavalier King Charles Spaniel',
    'Chesapeake Bay Retriever' => 'Retriever da Baía de Chesapeake', 'Chinese Crested' => 'Cristado Chinês', 'Chinese Shar-Pei' => 'Shar-Pei',
    'Chinook' => 'Chinook', 'Chow Chow' => 'Chow Chow', 'Clumber Spaniel' => 'Clumber Spaniel', 'Cocker Spaniel' => 'Cocker Spaniel Inglês',
    'Cocker Spaniel (American)' => 'Cocker Spaniel Americano', 'Coton de Tulear' => 'Coton de Tulear', 'Dalmatian' => 'Dálmata',
    'Doberman Pinscher' => 'Doberman', 'Dogo Argentino' => 'Dogo Argentino', 'Dutch Shepherd' => 'Pastor Holandês', 'English Setter' => 'Setter Inglês',
    'English Shepherd' => 'Pastor Inglês', 'English Springer Spaniel' => 'Springer Spaniel Inglês', 'English Toy Spaniel' => 'Toy Spaniel Inglês',
    'English Toy Terrier' => 'Toy Terrier Inglês', 'Eurasier' => 'Eurasier', 'Field Spaniel' => 'Field Spaniel',
    'Finnish Lapphund' => 'Cão Finlandês da Lapônia', 'Finnish Spitz' => 'Spitz Finlandês', 'French Bulldog' => 'Buldogue Francês',
    'German Pinscher' => 'Pinscher Alemão', 'German Shepherd Dog' => 'Pastor Alemão', 'German Shorthaired Pointer' => 'Braco Alemão de Pelo Curto',
    'Giant Schnauzer' => 'Schnauzer Gigante', 'Glen of Imaal Terrier' => 'Glen of Imaal Terrier', 'Golden Retriever' => 'Golden Retriever', 'Great dane' => 'Dogue alemão',
    'Gordon Setter' => 'Setter Gordon', 'Great Dane' => 'Dogue Alemão', 'Great Pyrenees' => 'Grande Pirineu', 'Greyhound' => 'Galgo Inglês',
    'Griffon Bruxellois' => 'Griffon de Bruxelas', 'Harrier' => 'Harrier', 'Irish Setter' => 'Setter Irlandês', 'Irish Wolfhound' => 'Wolfhound Irlandês',
    'Italian Greyhound' => 'Galguinho Italiano', 'Jack Russell Terrier' => 'Jack Russell Terrier', 'Japanese Chin' => 'Chin Japonês', 'Japanese Spitz' => 'Spitz Japonês',
    'Komondor' => 'Komondor', 'Labrador Retriever' => 'Labrador Retriever', 'Lhasa Apso' => 'Lhasa Apso', 'Maltese' => 'Maltês',
    'Newfoundland' => 'Terra-Nova', 'Pekingese' => 'Pequinês', 'Pembroke Welsh Corgi' => 'Welsh Corgi Pembroke', 'Pomeranian' => 'Pomerânia (Lulu)',
    'Poodle (Miniature)' => 'Poodle (Miniatura)', 'Poodle (Toy)' => 'Poodle (Toy)', 'Poodle (Standard)' => 'Poodle (Padrão)', 'Pug' => 'Pug',
    'Rottweiler' => 'Rottweiler', 'Saint Bernard' => 'São Bernardo', 'Samoyed' => 'Samoieda', 'Scottish Terrier' => 'Terrier Escocês',
    'Shetland Sheepdog' => 'Pastor de Shetland', 'Shiba Inu' => 'Shiba Inu', 'Shih Tzu' => 'Shih Tzu', 'Siberian Husky' => 'Husky Siberiano',
    'Staffordshire Bull Terrier' => 'Staffordshire Bull Terrier', 'Weimaraner' => 'Weimaraner', 'Whippet' => 'Whippet', 'Yorkshire Terrier' => 'Yorkshire Terrier'
];

$traducoesTermos = [
    'Stubborn' => 'Teimoso', 'Curious' => 'Curioso', 'Playful' => 'Brincalhão', 'Adventurous' => 'Aventureiro',
    'Active' => 'Ativo', 'Fun-loving' => 'Divertido', 'Aloof' => 'Reservado', 'Clownish' => 'Engraçado',
    'Dignified' => 'Digno', 'Independent' => 'Independente', 'Happy' => 'Feliz', 'Wild' => 'Selvagem',
    'Hardworking' => 'Trabalhador', 'Dutiful' => 'Dedicado', 'Outgoing' => 'Extrovertido', 'Friendly' => 'Amigável',
    'Alert' => 'Alerta', 'Confident' => 'Confiante', 'Intelligent' => 'Inteligente', 'Courageous' => 'Corajoso',
    'Loyal' => 'Leal', 'Brave' => 'Valente', 'Docile' => 'Dócil', 'Responsive' => 'Receptivo',
    'Composed' => 'Composto', 'Receptive' => 'Receptivo', 'Faithful' => 'Fiel', 'Loving' => 'Amoroso',
    'Protective' => 'Protetor', 'Trainable' => 'Treinável', 'Responsible' => 'Responsável', 'Energetic' => 'Enérgico',
    'Gentle' => 'Gentil', 'Affectionate' => 'Afetuoso', 'Devoted' => 'Devotado', 'Assertive' => 'Assertivo',
    'Dominant' => 'Dominante', 'Strong Willed' => 'Determinado', 'Obedient' => 'Obediente', 'Reserved' => 'Reservado',
    'Kind' => 'Gentil', 'Sweet-Tempered' => 'Meigo', 'Tenacious' => 'Persistente', 'Attentive' => 'Atencioso',
    'Steady' => 'Estável', 'Bold' => 'Ousado', 'Proud' => 'Orgulhoso', 'Reliable' => 'Confiável',
    'Fearless' => 'Destemido', 'Lively' => 'Vívido', 'Self-assured' => 'Autoconfiante', 'Cautious' => 'Cauteloso',
    'Eager' => 'Ansioso', 'Good-natured' => 'Bondoso', 'Spirited' => 'Vigoroso', 'Companionable' => 'Companheiro',
    'Even Tempered' => 'Temperamento Equilibrado', 'Rugged' => 'Robusto', 'Fierce' => 'Feroz', 'Refined' => 'Refinado',
    'Joyful' => 'Alegre', 'Agile' => 'Ágil', 'Amiable' => 'Amável', 'Excitable' => 'Excitável',
    'Determined' => 'Determinado', 'Self-confidence' => 'Autoconfiante', 'Hardy' => 'Resistente', 'Calm' => 'Calmo',
    'Good-tempered' => 'Bom Temperamento', 'Watchful' => 'Vigilante', 'Feisty' => 'Valente', 'Cheerful' => 'Alegre',
    'Sensitive' => 'Sensível', 'Easygoing' => 'Fácil de Lidar', 'Adaptable' => 'Adaptável', 'Trusting' => 'Confiante',
    'Lovable' => 'Adorável', 'Territorial' => 'Territorial', 'Keen' => 'Entusiasmado', 'Familial' => 'Familiar',
    'Rational' => 'Racional', 'Bright' => 'Brilhante', 'Quick' => 'Rápido', 'Inquisitive' => 'Inquisitivo',
    'Sociable' => 'Sociável', 'Patient' => 'Paciente', 'Suspicious' => 'Desconfiado', 'Great-hearted' => 'Grandioso',
    'Merry' => 'Alegre', 'Vocal' => 'Barulhento', 'Quiet' => 'Quieto', 'Powerful' => 'Poderoso',
    'Gay' => 'Alegre', 'Athletic' => 'Atlético', 'Toy' => 'Toy (Pequeno Porte)', 'Hound' => 'Hound (Cão de Caça)',
    'Terrier' => 'Terrier', 'Working' => 'Trabalho', 'Mixed' => 'Misto (SRD)', 'Non-Sporting' => 'Não-Esportivo',
    'Sporting' => 'Esportivo', 'Herding' => 'Pastoreio', 'years' => 'anos'
];

$traducoesOrigens = [
    'Germany' => 'Alemanha', 'France' => 'França', 'United Kingdom' => 'Reino Unido', 'England' => 'Inglaterra',
    'Scotland' => 'Escócia', 'Wales' => 'País de Gales', 'Ireland' => 'Irlanda', 'Belgium' => 'Bélgica',
    'Netherlands' => 'Holanda', 'Switzerland' => 'Suíça', 'Italy' => 'Itália', 'Spain' => 'Espanha',
    'Portugal' => 'Portugal', 'Russia' => 'Rússia', 'Siberia' => 'Sibéria', 'Hungary' => 'Hungria',
    'Poland' => 'Polônia', 'Finland' => 'Finlândia', 'United States' => 'Estados Unidos', 'Canada' => 'Canadá',
    'Mexico' => 'México', 'Brazil' => 'Brasil', 'Argentina' => 'Argentina', 'Australia' => 'Austrália',
    'China' => 'China', 'Japan' => 'Japão', 'Tibet' => 'Tibet', 'Afghanistan' => 'Afeganistão',
    'Iran' => 'Irã', 'Pakistan' => 'Paquistão', 'Turkey' => 'Turquia', 'Egypt' => 'Egito',
    'South Africa' => 'África do Sul', 'Madagascar' => 'Madagascar'
];